### ISSUE TITLE
JsonSubtypes.KnownSubType with Lambda

### ISSUE THREAD

**Issue by sbeaudoin** [manuc66/JsonSubTypes#106]
### Introduction
On my json string, the content of the property I define for the subtype is a flags enum.  I would like an overload of KnownSubType where I can specify a lambda function who will receive the json property value as a parameter and in return, will provide a boolean true or false, indicating if the specified subtype should be used.

### Example
For example, the json string property "provides" can contain the following "player, reader, controller".  I want to create a polymorphic instance "reader" if the string "reader" is found in the json property.

At this time, I can't, because the value specified in the KnownSubType will try to match the ENTIRE value of the json string.

This could be compensated with something like this :

`[JsonSubtypes.KnownSubType(typeof(ReaderClass), s=>s.Contains("reader"))]`

**Comment by manuc66** [comment]
Hi,

Your proposition will not work because CLR restrict attribute parameter types, see : https://github.com/dotnet/csharplang/blob/master/spec/attributes.md#attribute-parameter-types

Maybe making this method virtual might help you define your own converter:
https://github.com/manuc66/JsonSubTypes/blob/master/JsonSubTypes/JsonSubtypes.cs#L224

Or using code instead of attributes like done with : https://github.com/manuc66/JsonSubTypes#registration

**Comment by manuc66** [comment]
@sbeaudoin 

Could you match with a property that is only present in 'reader'

```csharp
[JsonSubtypes.KnownSubTypeWithProperty(typeof(Reader), "readerName")]
``

**Comment by sbeaudoin** [comment]
I used another aproach, sorry.
