### ISSUE TITLE
Serialize with type

### ISSUE THREAD

**Issue by gfilisteevrocket** [manuc66/JsonSubTypes#42]
Hi @manuc66, 
How to serialize into JSON include typeinfo from anotation. 
[JsonConverter(typeof(JsonSubtypes), "_type")]

**Comment by manuc66** [comment]
Hi @gfilisteevrocket,

If you use the converter attribute you need to define the property on (base) class in order to emit that property when serializing.

If you use dynamic registration it's not mandatory, see: [SerializeObject and DeserializeObject with custom type property only present in JSON](https://github.com/manuc66/JsonSubTypes#serializeobject-and-deserializeobject-with-custom-type-property-only-present-in-json)

Best regards
